[2022-04-16 01:52:23,813] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: analyze_json_data.processParsedData 2022-04-11T00:00:00+00:00 [queued]>
[2022-04-16 01:52:23,825] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: analyze_json_data.processParsedData 2022-04-11T00:00:00+00:00 [queued]>
[2022-04-16 01:52:23,825] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-04-16 01:52:23,825] {taskinstance.py:1043} INFO - Starting attempt 1 of 4
[2022-04-16 01:52:23,826] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-04-16 01:52:23,832] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): processParsedData> on 2022-04-11T00:00:00+00:00
[2022-04-16 01:52:23,834] {standard_task_runner.py:52} INFO - Started process 422 to run task
[2022-04-16 01:52:23,837] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'analyze_json_data', 'processParsedData', '2022-04-11T00:00:00+00:00', '--job-id', '176', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dagRun.py', '--cfg-path', '/tmp/tmp6so1e612', '--error-file', '/tmp/tmpktgr29po']
[2022-04-16 01:52:23,839] {standard_task_runner.py:77} INFO - Job 176: Subtask processParsedData
[2022-04-16 01:52:23,868] {logging_mixin.py:104} INFO - Running <TaskInstance: analyze_json_data.processParsedData 2022-04-11T00:00:00+00:00 [running]> on host 184ae5fa8a0d
[2022-04-16 01:52:23,899] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Renato_Otescu
AIRFLOW_CTX_DAG_ID=analyze_json_data
AIRFLOW_CTX_TASK_ID=processParsedData
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-11T00:00:00+00:00
[2022-04-16 01:52:23,899] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-04-16 01:52:23,900] {bash.py:158} INFO - Running command: python /opt/airflow/sparkFiles/sparkProcess.py
[2022-04-16 01:52:23,905] {bash.py:169} INFO - Output:
[2022-04-16 01:52:25,020] {bash.py:173} INFO - WARNING: An illegal reflective access operation has occurred
[2022-04-16 01:52:25,020] {bash.py:173} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/airflow/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2022-04-16 01:52:25,020] {bash.py:173} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2022-04-16 01:52:25,020] {bash.py:173} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2022-04-16 01:52:25,020] {bash.py:173} INFO - WARNING: All illegal access operations will be denied in a future release
[2022-04-16 01:52:25,198] {bash.py:173} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2022-04-16 01:52:25,205] {bash.py:173} INFO - Setting default log level to "WARN".
[2022-04-16 01:52:25,205] {bash.py:173} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2022-04-16 01:52:25,333] {bash.py:173} INFO - 22/04/16 01:52:25 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2022-04-16 01:52:25,866] {bash.py:173} INFO - 22/04/16 01:52:25 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2022-04-16 01:52:31,453] {bash.py:173} INFO - 22/04/16 01:52:31 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
[2022-04-16 01:52:31,467] {bash.py:173} INFO - 22/04/16 01:52:31 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
[2022-04-16 01:52:31,480] {bash.py:173} INFO - 22/04/16 01:52:31 WARN package: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
[2022-04-16 01:52:31,689] {bash.py:173} INFO - 22/04/16 01:52:31 ERROR Executor: Exception in task 0.0 in stage 2.0 (TID 2)
[2022-04-16 01:52:31,689] {bash.py:173} INFO - java.io.FileNotFoundException:
[2022-04-16 01:52:31,689] {bash.py:173} INFO - File file:/opt/airflow/sparkFiles/parsedData.csv does not exist
[2022-04-16 01:52:31,689] {bash.py:173} INFO - 
[2022-04-16 01:52:31,689] {bash.py:173} INFO - It is possible the underlying files have been updated. You can explicitly invalidate
[2022-04-16 01:52:31,690] {bash.py:173} INFO - the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by
[2022-04-16 01:52:31,690] {bash.py:173} INFO - recreating the Dataset/DataFrame involved.
[2022-04-16 01:52:31,690] {bash.py:173} INFO - 
[2022-04-16 01:52:31,690] {bash.py:173} INFO - 	at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:506)
[2022-04-16 01:52:31,690] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:130)
[2022-04-16 01:52:31,690] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:187)
[2022-04-16 01:52:31,690] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:104)
[2022-04-16 01:52:31,690] {bash.py:173} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2022-04-16 01:52:31,690] {bash.py:173} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2022-04-16 01:52:31,690] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2022-04-16 01:52:31,690] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
[2022-04-16 01:52:31,690] {bash.py:173} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2022-04-16 01:52:31,690] {bash.py:173} INFO - 	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:140)
[2022-04-16 01:52:31,690] {bash.py:173} INFO - 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
[2022-04-16 01:52:31,690] {bash.py:173} INFO - 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
[2022-04-16 01:52:31,690] {bash.py:173} INFO - 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
[2022-04-16 01:52:31,690] {bash.py:173} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2022-04-16 01:52:31,691] {bash.py:173} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
[2022-04-16 01:52:31,691] {bash.py:173} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
[2022-04-16 01:52:31,691] {bash.py:173} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
[2022-04-16 01:52:31,691] {bash.py:173} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-04-16 01:52:31,691] {bash.py:173} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-04-16 01:52:31,691] {bash.py:173} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2022-04-16 01:52:31,701] {bash.py:173} INFO - 22/04/16 01:52:31 WARN TaskSetManager: Lost task 0.0 in stage 2.0 (TID 2) (184ae5fa8a0d executor driver): java.io.FileNotFoundException:
[2022-04-16 01:52:31,701] {bash.py:173} INFO - File file:/opt/airflow/sparkFiles/parsedData.csv does not exist
[2022-04-16 01:52:31,701] {bash.py:173} INFO - 
[2022-04-16 01:52:31,701] {bash.py:173} INFO - It is possible the underlying files have been updated. You can explicitly invalidate
[2022-04-16 01:52:31,701] {bash.py:173} INFO - the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by
[2022-04-16 01:52:31,701] {bash.py:173} INFO - recreating the Dataset/DataFrame involved.
[2022-04-16 01:52:31,701] {bash.py:173} INFO - 
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:506)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:130)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:187)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:104)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:140)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
[2022-04-16 01:52:31,702] {bash.py:173} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-04-16 01:52:31,703] {bash.py:173} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-04-16 01:52:31,703] {bash.py:173} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2022-04-16 01:52:31,703] {bash.py:173} INFO - 
[2022-04-16 01:52:31,703] {bash.py:173} INFO - 22/04/16 01:52:31 ERROR TaskSetManager: Task 0 in stage 2.0 failed 1 times; aborting job
[2022-04-16 01:52:31,713] {bash.py:173} INFO - /home/airflow/.local/lib/python3.6/site-packages/pyspark/context.py:238: FutureWarning: Python 3.6 support is deprecated in Spark 3.2.
[2022-04-16 01:52:31,714] {bash.py:173} INFO -   FutureWarning
[2022-04-16 01:52:31,715] {bash.py:173} INFO - Traceback (most recent call last):
[2022-04-16 01:52:31,715] {bash.py:173} INFO -   File "/opt/airflow/sparkFiles/sparkProcess.py", line 48, in <module>
[2022-04-16 01:52:31,715] {bash.py:173} INFO -     result.toPandas().to_csv('/opt/airflow/sparkFiles/results.csv',
[2022-04-16 01:52:31,715] {bash.py:173} INFO -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/pandas/conversion.py", line 157, in toPandas
[2022-04-16 01:52:31,715] {bash.py:173} INFO -     pdf = pd.DataFrame.from_records(self.collect(), columns=self.columns)
[2022-04-16 01:52:31,716] {bash.py:173} INFO -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/dataframe.py", line 693, in collect
[2022-04-16 01:52:31,716] {bash.py:173} INFO -     sock_info = self._jdf.collectToPython()
[2022-04-16 01:52:31,716] {bash.py:173} INFO -   File "/home/airflow/.local/lib/python3.6/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2022-04-16 01:52:31,716] {bash.py:173} INFO -     answer, self.gateway_client, self.target_id, self.name)
[2022-04-16 01:52:31,716] {bash.py:173} INFO -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/utils.py", line 111, in deco
[2022-04-16 01:52:31,716] {bash.py:173} INFO -     return f(*a, **kw)
[2022-04-16 01:52:31,716] {bash.py:173} INFO -   File "/home/airflow/.local/lib/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
[2022-04-16 01:52:31,716] {bash.py:173} INFO -     format(target_id, ".", name), value)
[2022-04-16 01:52:31,716] {bash.py:173} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o657.collectToPython.
[2022-04-16 01:52:31,716] {bash.py:173} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 1 times, most recent failure: Lost task 0.0 in stage 2.0 (TID 2) (184ae5fa8a0d executor driver): java.io.FileNotFoundException:
[2022-04-16 01:52:31,716] {bash.py:173} INFO - File file:/opt/airflow/sparkFiles/parsedData.csv does not exist
[2022-04-16 01:52:31,716] {bash.py:173} INFO - 
[2022-04-16 01:52:31,716] {bash.py:173} INFO - It is possible the underlying files have been updated. You can explicitly invalidate
[2022-04-16 01:52:31,716] {bash.py:173} INFO - the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by
[2022-04-16 01:52:31,716] {bash.py:173} INFO - recreating the Dataset/DataFrame involved.
[2022-04-16 01:52:31,716] {bash.py:173} INFO - 
[2022-04-16 01:52:31,717] {bash.py:173} INFO - 	at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:506)
[2022-04-16 01:52:31,717] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:130)
[2022-04-16 01:52:31,717] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:187)
[2022-04-16 01:52:31,717] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:104)
[2022-04-16 01:52:31,717] {bash.py:173} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2022-04-16 01:52:31,717] {bash.py:173} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2022-04-16 01:52:31,717] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2022-04-16 01:52:31,717] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
[2022-04-16 01:52:31,717] {bash.py:173} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2022-04-16 01:52:31,717] {bash.py:173} INFO - 	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:140)
[2022-04-16 01:52:31,717] {bash.py:173} INFO - 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
[2022-04-16 01:52:31,717] {bash.py:173} INFO - 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
[2022-04-16 01:52:31,717] {bash.py:173} INFO - 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
[2022-04-16 01:52:31,717] {bash.py:173} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2022-04-16 01:52:31,718] {bash.py:173} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
[2022-04-16 01:52:31,718] {bash.py:173} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
[2022-04-16 01:52:31,718] {bash.py:173} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
[2022-04-16 01:52:31,718] {bash.py:173} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-04-16 01:52:31,718] {bash.py:173} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-04-16 01:52:31,718] {bash.py:173} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2022-04-16 01:52:31,718] {bash.py:173} INFO - 
[2022-04-16 01:52:31,718] {bash.py:173} INFO - Driver stacktrace:
[2022-04-16 01:52:31,718] {bash.py:173} INFO - 	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2454)
[2022-04-16 01:52:31,718] {bash.py:173} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2403)
[2022-04-16 01:52:31,718] {bash.py:173} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2402)
[2022-04-16 01:52:31,718] {bash.py:173} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2022-04-16 01:52:31,718] {bash.py:173} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2022-04-16 01:52:31,718] {bash.py:173} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2022-04-16 01:52:31,718] {bash.py:173} INFO - 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2402)
[2022-04-16 01:52:31,719] {bash.py:173} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1160)
[2022-04-16 01:52:31,719] {bash.py:173} INFO - 	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1160)
[2022-04-16 01:52:31,719] {bash.py:173} INFO - 	at scala.Option.foreach(Option.scala:407)
[2022-04-16 01:52:31,719] {bash.py:173} INFO - 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1160)
[2022-04-16 01:52:31,719] {bash.py:173} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2642)
[2022-04-16 01:52:31,719] {bash.py:173} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2584)
[2022-04-16 01:52:31,719] {bash.py:173} INFO - 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2573)
[2022-04-16 01:52:31,719] {bash.py:173} INFO - 	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2022-04-16 01:52:31,719] {bash.py:173} INFO - Caused by: java.io.FileNotFoundException:
[2022-04-16 01:52:31,719] {bash.py:173} INFO - File file:/opt/airflow/sparkFiles/parsedData.csv does not exist
[2022-04-16 01:52:31,719] {bash.py:173} INFO - 
[2022-04-16 01:52:31,719] {bash.py:173} INFO - It is possible the underlying files have been updated. You can explicitly invalidate
[2022-04-16 01:52:31,719] {bash.py:173} INFO - the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by
[2022-04-16 01:52:31,719] {bash.py:173} INFO - recreating the Dataset/DataFrame involved.
[2022-04-16 01:52:31,719] {bash.py:173} INFO - 
[2022-04-16 01:52:31,719] {bash.py:173} INFO - 	at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:506)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:130)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:187)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:104)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:140)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2022-04-16 01:52:31,720] {bash.py:173} INFO - 
[2022-04-16 01:52:32,163] {bash.py:177} INFO - Command exited with return code 1
[2022-04-16 01:52:32,171] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-04-16 01:52:32,173] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=analyze_json_data, task_id=processParsedData, execution_date=20220411T000000, start_date=20220416T015223, end_date=20220416T015232
[2022-04-16 01:52:32,221] {local_task_job.py:146} INFO - Task exited with return code 1
