[2022-04-16 01:54:11,525] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: analyze_json_data.processParsedData 2022-04-11T00:00:00+00:00 [queued]>
[2022-04-16 01:54:11,539] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: analyze_json_data.processParsedData 2022-04-11T00:00:00+00:00 [queued]>
[2022-04-16 01:54:11,539] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-04-16 01:54:11,539] {taskinstance.py:1043} INFO - Starting attempt 4 of 4
[2022-04-16 01:54:11,539] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-04-16 01:54:11,545] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): processParsedData> on 2022-04-11T00:00:00+00:00
[2022-04-16 01:54:11,548] {standard_task_runner.py:52} INFO - Started process 1588 to run task
[2022-04-16 01:54:11,551] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'analyze_json_data', 'processParsedData', '2022-04-11T00:00:00+00:00', '--job-id', '183', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dagRun.py', '--cfg-path', '/tmp/tmp7wwxq7j3', '--error-file', '/tmp/tmp4_44b2ij']
[2022-04-16 01:54:11,553] {standard_task_runner.py:77} INFO - Job 183: Subtask processParsedData
[2022-04-16 01:54:11,587] {logging_mixin.py:104} INFO - Running <TaskInstance: analyze_json_data.processParsedData 2022-04-11T00:00:00+00:00 [running]> on host 184ae5fa8a0d
[2022-04-16 01:54:11,616] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Renato_Otescu
AIRFLOW_CTX_DAG_ID=analyze_json_data
AIRFLOW_CTX_TASK_ID=processParsedData
AIRFLOW_CTX_EXECUTION_DATE=2022-04-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-11T00:00:00+00:00
[2022-04-16 01:54:11,616] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-04-16 01:54:11,617] {bash.py:158} INFO - Running command: python /opt/airflow/sparkFiles/sparkProcess.py
[2022-04-16 01:54:11,625] {bash.py:169} INFO - Output:
[2022-04-16 01:54:12,642] {bash.py:173} INFO - WARNING: An illegal reflective access operation has occurred
[2022-04-16 01:54:12,642] {bash.py:173} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/airflow/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2022-04-16 01:54:12,642] {bash.py:173} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2022-04-16 01:54:12,642] {bash.py:173} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2022-04-16 01:54:12,643] {bash.py:173} INFO - WARNING: All illegal access operations will be denied in a future release
[2022-04-16 01:54:12,817] {bash.py:173} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2022-04-16 01:54:12,818] {bash.py:173} INFO - Setting default log level to "WARN".
[2022-04-16 01:54:12,818] {bash.py:173} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2022-04-16 01:54:12,950] {bash.py:173} INFO - 22/04/16 01:54:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2022-04-16 01:54:14,388] {bash.py:173} INFO - /home/airflow/.local/lib/python3.6/site-packages/pyspark/context.py:238: FutureWarning: Python 3.6 support is deprecated in Spark 3.2.
[2022-04-16 01:54:14,388] {bash.py:173} INFO -   FutureWarning
[2022-04-16 01:54:14,393] {bash.py:173} INFO - Traceback (most recent call last):
[2022-04-16 01:54:14,393] {bash.py:173} INFO -   File "/opt/airflow/sparkFiles/sparkProcess.py", line 22, in <module>
[2022-04-16 01:54:14,394] {bash.py:173} INFO -     ignoreTrailingWhiteSpace=True)
[2022-04-16 01:54:14,394] {bash.py:173} INFO -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/readwriter.py", line 410, in csv
[2022-04-16 01:54:14,394] {bash.py:173} INFO -     return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2022-04-16 01:54:14,394] {bash.py:173} INFO -   File "/home/airflow/.local/lib/python3.6/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2022-04-16 01:54:14,394] {bash.py:173} INFO -     answer, self.gateway_client, self.target_id, self.name)
[2022-04-16 01:54:14,394] {bash.py:173} INFO -   File "/home/airflow/.local/lib/python3.6/site-packages/pyspark/sql/utils.py", line 117, in deco
[2022-04-16 01:54:14,394] {bash.py:173} INFO -     raise converted from None
[2022-04-16 01:54:14,394] {bash.py:173} INFO - pyspark.sql.utils.AnalysisException: Path does not exist: file:/opt/airflow/sparkFiles/parsedData.csv
[2022-04-16 01:54:14,816] {bash.py:177} INFO - Command exited with return code 1
[2022-04-16 01:54:14,822] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-04-16 01:54:14,823] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=analyze_json_data, task_id=processParsedData, execution_date=20220411T000000, start_date=20220416T015411, end_date=20220416T015414
[2022-04-16 01:54:14,848] {local_task_job.py:146} INFO - Task exited with return code 1
